### Find All Content
GET http://localhost:8080/api/content

### Get content by ID
GET http://localhost:8080/api/content

### Create new Content
POST http://localhost:8080/api/content
Content-Type: application/json

{
  "id": 2,
  "title": "My second blog post",
  "desc": "My second blog post",
  "status": "IDEA",
  "contentType": "ARTICLE",
  "dateCreated": "2024-03-11T23:36:51.4721715",
  "dateUpdated": null,
  "url": ""
}



### Update existing Content
PUT http://localhost:8080/api/content/1
Content-Type: application/json

{
  "id": 1,
  "title": "MY FIRST POST !!",
  "desc": "MY FIRST POST !!",
  "status": "IDEA",
  "contentType": "ARTICLE",
  "dateCreated": "2024-03-11T23:36:51.4721715",
  "dateUpdated": "2024-03-11T23:36:51.4721715",
  "url": "http://localhost:8080/my-first-blog-post"
}

### Delete By Id
DELETE http://localhost:8080/api/content/2